apply plugin: 'com.google.firebase.crashlytics'
android {
    buildTypes {
        debug {
            firebaseCrashlytics {
                mappingFileUploadEnabled false
            }
        }
        release {
            firebaseCrashlytics {
                nativeSymbolUploadEnabled true
                unstrippedNativeLibsDir "obj/local"
            }
        }
    }
}
